### ISSUE TITLE
Save then restore state with IN#2 in Lisa Assembler v2.5D

### ISSUE THREAD

**Issue by dvot197007** [AppleWin/AppleWin#486]
Hello,

After enabling TCP, I loaded the Lisa assembler v2.5D disk (from Asimov) into drive 1. Then ctrl-D (to allow DOS commands) followed by IN#2. Then doing a save and restore state drops me into the monitor. This problem also occurs in AppleWin 1.25. 

The reason for wanting to do this is to automatically get the Lisa assembler into a state where I can pipe commands over TCP.

Thanks,
DOT

**Comment by tomcw** [comment]
Repro:
* Boot to AppleSoft
* IN#2
* Save state, then load state

Crashes to monitor

**Comment by tomcw** [comment]
I guess that the state of the SSC's expansion ROM isn't being correctly (saved?) restored to $C800-CFFF.

**Comment by tomcw** [comment]
As suspected, the expansion ROM wasn't being correct restored and the PC was running in this space,
Fixed in 3a5bf01.
To do: Add a regression test.

**Comment by dvot197007** [comment]
Fantastic - thanks very much.
David
----Original message----
From : notifications@github.com
Date : 22/09/2017 - 22:27 (GMTST)
To : AppleWin@noreply.github.com
Cc : dvot1970@btinternet.com, author@noreply.github.com
Subject : Re: [AppleWin/AppleWin] Save then restore state with IN#2 in Lisa Assembler v2.5D (#486)
As suspected, the expansion ROM wasn't being correct restored and the PC was running in this space,
Fixed in 3a5bf01.
To do: Add a regression test.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
  
  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AppleWin/AppleWin","title":"AppleWin/AppleWin","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/AppleWin/AppleWin"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tomcw in #486: As suspected, the expansion ROM wasn't being correct restored and the PC was running in this space,\r\nFixed in 3a5bf01.\r\nTo do: Add a regression test."}],"action":{"name":"View Issue","url":"https://github.com/AppleWin/AppleWin/issues/486#issuecomment-331564710"}}}

**Comment by dvot197007** [comment]
That seems to have fixed the problem - I built from the new source using Visual Studio 2015 and my problem with the Lisa assembler and IN#2 has gone. 
Do I need to close the issue or will someone else do that?
Also, will the bug fix be rolled into the current version of AppleWin or will it have to wait for the next release?
Anyway, thanks very much,
David

**Comment by tomcw** [comment]
Thanks for confirming the fix.

>Do I need to close the issue or will someone else do that?

No. I need to add a regression test. Then I will close this bug.

>Also, will the bug fix be rolled into the current version of AppleWin or will it have to wait for the next release?

What version of AppleWin are you using?

Recently I've been doing "experimental" releases for small, targeted updates - mainly for specific users. The latest is 1.26.3.0, [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.3.0).
Since this release (2 months ago) there have been some minor fixes, mainly to the built-in debugger.

And the latest "official" release was mid-Feb, 7 months ago... so maybe time to put out a new official version.

**Comment by tomcw** [comment]
Added test: https://github.com/AppleWin/AppleWin-Test/commit/8e08343f9b5a96ac678d61954f0eac4f2fdf6431

**Comment by tomcw** [comment]
NB. This bug still exists in v1 save-states, but I have no plans to update support for this old format.

**Comment by tomcw** [comment]
FYI, new experimental release build 1.26.3.1 [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.3.1), which includes this fix.

**Comment by dvot197007** [comment]
Thank you - David
----Original message----
From : notifications@github.com
Date : 30/09/2017 - 13:29 (GMTST)
To : AppleWin@noreply.github.com
Cc : dvot1970@btinternet.com, author@noreply.github.com
Subject : Re: [AppleWin/AppleWin] Save then restore state with IN#2 in Lisa Assembler v2.5D (#486)
FYI, new experimental release build 1.26.3.1 here, which includes this fix.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
  
  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AppleWin/AppleWin","title":"AppleWin/AppleWin","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/AppleWin/AppleWin"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tomcw in #486: FYI, new experimental release build 1.26.3.1 [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.3.1), which includes this fix."}],"action":{"name":"View Issue","url":"https://github.com/AppleWin/AppleWin/issues/486#issuecomment-333305478"}}}
